// <auto-generated />
using System;
using ClubModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Week8ClassLibrary2023.DataLayer.Migrations
{
    [DbContext(typeof(ClubsContext))]
    partial class ClubsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubModels.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("adminID")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.ToTable("Club");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            ClubName = "Basketball Club",
                            CreationDate = new DateTime(2023, 11, 8, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(1789),
                            adminID = 1
                        },
                        new
                        {
                            ClubId = 2,
                            ClubName = "Football Club",
                            CreationDate = new DateTime(2023, 11, 8, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(1870),
                            adminID = 2
                        },
                        new
                        {
                            ClubId = 3,
                            ClubName = "Boxing Club",
                            CreationDate = new DateTime(2023, 11, 8, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(1880),
                            adminID = 3
                        });
                });

            modelBuilder.Entity("ClubModels.ClubEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.HasIndex("ClubId");

                    b.ToTable("ClubEvent");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            ClubId = 1,
                            EndDateTime = new DateTime(2023, 12, 8, 14, 33, 21, 339, DateTimeKind.Local).AddTicks(2357),
                            Location = "Tallaght, Dublin",
                            StartDateTime = new DateTime(2023, 12, 8, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(2344),
                            Venue = "National Basketball Arena"
                        },
                        new
                        {
                            EventID = 2,
                            ClubId = 2,
                            EndDateTime = new DateTime(2024, 1, 7, 13, 33, 21, 339, DateTimeKind.Local).AddTicks(2374),
                            Location = "Ballsbridge, Dublin",
                            StartDateTime = new DateTime(2024, 1, 7, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(2368),
                            Venue = "Aviva Stadium"
                        },
                        new
                        {
                            EventID = 3,
                            ClubId = 3,
                            EndDateTime = new DateTime(2024, 2, 6, 12, 33, 21, 339, DateTimeKind.Local).AddTicks(2388),
                            Location = "South Circular Road, Dublin",
                            StartDateTime = new DateTime(2024, 2, 6, 10, 33, 21, 339, DateTimeKind.Local).AddTicks(2383),
                            Venue = "National Boxing Stadium"
                        });
                });

            modelBuilder.Entity("ClubModels.ClubEvent", b =>
                {
                    b.HasOne("ClubModels.Club", "associatedClub")
                        .WithMany("clubEvents")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("associatedClub");
                });

            modelBuilder.Entity("ClubModels.Club", b =>
                {
                    b.Navigation("clubEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
