@port = 3001
@contactPath = /api/v1/contacts

### 
# POST Request to create a new contact 
POST http://localhost:{{port}}{{contactPath}} HTTP/1.1
content-type: application/json

{
    "name": "Jack Monaghan",
    "phoneNumber": "0871234567",
    "email": "s00227213@atu.ie"
}

### @name getAllContacts
# GET Request to fetch all contacts
GET http://localhost:{{port}}{{contactPath}} HTTP/1.1



### @name getSpecificContact
# GET request for a specific contact
GET http://localhost:{{port}}{{contactPath}}/{{getAllContacts.response.body[0]._id}} HTTP/1.1

### @name updateSpecificContact
# PUT request to update a specific contact
PUT http://localhost:{{port}}{{contactPath}}/{{getAllContacts.response.body[0]._id}} HTTP/1.1
content-type: application/json

{
    "name": "Updated Name",
    "phoneNumber": "Updated Phone",
    "email": "updatedemail@atu.ie"
}

### @name deleteSpecificContact
# DELETE request for a specific contact
DELETE http://localhost:{{port}}{{contactPath}}/{{getAllContacts.response.body[0]._id}} HTTP/1.1
